### ISSUE TITLE
Discussion: Remove borgmatic from index. 

### ISSUE THREAD

**Issue by modem7** [borgmatic-collective/pypi#11]
@grantbevis - what are your thoughts on removing borgmatic and apprise from the index?

As Borgmatic and Apprise are pure python wheels, there's no need to manage it in the index. It gives no value-add from the additional management as there's no additional build time involved grabbing it from pypi.

Only Borg and llfuse really do problematic bits as they're not pure python.

**Comment by grantbevis** [comment]
Sure mate makes sense to me

**Comment by modem7** [comment]
Turns out this is a bad decision.

Whilst Borgmatic and Apprise themselves are pure python, not all their dependencies are. 

Leave as is for now.
