### ISSUE TITLE
borg 1.2.2 build

### ISSUE THREAD

**Issue by grantbevis** [borgmatic-collective/pypi#6]
@modem7 please can you update this repo to have borg 1.2.2 built please?

I thought adding this would make pip on the borgmatic docker image build faster as it'll use this as a wheel cache, not out right stop the image build if a package is missing.

We might need to abandon this idea as I don't like that the image build depends on something external that could cause it to fail building.

**Comment by modem7** [comment]
Aye, I was swamped with work.

Will get this built now.

**Comment by modem7** [comment]
All built.

Awaiting github actions to build the index.

**Comment by grantbevis** [comment]
Cheers bro @modem7
